name: ModalView Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: macOS-10.14
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run tests
      run: |
        sudo xcode-select --switch /Applications/Xcode_11.app
        swift test
