name: ModalView Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: macOS-10.15
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Run tests
      run: swift test
